package space.nebula.nexus.enums;

/**
 * Stable notification identifiers shared by business rules and delivery
 * preferences.
 */
public enum NotificationType {
	COMMENT_APPROVED, COMMENT_REJECTED, COMMENT_REPLY, POST_COMMENT, MOMENT_COMMENT, GUESTBOOK_COMMENT, COMMENT_PENDING_REVIEW, COMMENT_FLAGGED, COMMENT_REPORT_RECEIVED, COMMENT_REPORT_RESOLVED, CATEGORY_POST, POST_PENDING_REVIEW, POST_REJECTED, POST_PUBLISHED, POST_SCHEDULED, POST_SCHEDULE_CANCELED, POST_ARCHIVED, POST_REPORT_RECEIVED, POST_REPORT_RESOLVED, FRIEND_LINK_APPLICATION, FRIEND_LINK_APPROVED, FRIEND_LINK_REJECTED, USER_PENDING_REVIEW
}
