spring:
  application:
    name: nexus
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: "common,dev"
      test: "common,test"
      prod: "common,prod"
  flyway:
    validate-on-migrate: false # Bypass legacy checksum mismatches globally across all profiles
