-- V100: Canal user provisioning
--
-- The Canal database user requires global replication privileges.
-- It is provisioned separately by the deployment process using
-- a MySQL administrative account.
--
-- No application schema changes are required here.
