CREATE TABLE `sys_operation_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `method_name` VARCHAR(255) DEFAULT NULL,
  `request_method` VARCHAR(20) DEFAULT NULL,
  `request_url` VARCHAR(500) DEFAULT NULL,
  `ip_address` VARCHAR(100) DEFAULT NULL,
  `user_agent` VARCHAR(500) DEFAULT NULL,
  `parameters` TEXT DEFAULT NULL,
  `result` TEXT DEFAULT NULL,
  `duration` BIGINT DEFAULT NULL,
  `status` INT DEFAULT NULL COMMENT '1: Success, 0: Failure',
  `error_message` TEXT DEFAULT NULL,
  `trace_id` VARCHAR(100) DEFAULT NULL,
  `created_by` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(100) DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`id`),
  INDEX `idx_sys_op_username` (`username`),
  INDEX `idx_sys_op_status` (`status`),
  INDEX `idx_sys_op_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
